jobs:
  build:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run build
version: 2.1
orbs:
  node: circleci/node@3.0.0

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
